### ISSUE TITLE
Kostaltyn has no unique icons + flip rewards

### ISSUE THREAD

**Issue by OhManTFE** [msolefonte/vco#138]
Issue 1:
Route 3: Altdorf + Marienburg rewards need to be flipped. Income from Ports +30 goes to Marienburg and melee defence goes to altdorf.

Issue 2: Need new icons. Icons changed by me in myedits packfile.

**Comment by OhManTFE** [comment]
Fixed and will go live with next patch.

**Comment by msolefonte** [comment]
Reopened. I left a comment on the other one.

**Comment by OhManTFE** [comment]
Route 3's override text needs to be its own separate dummy text, because it is removing important information for the player's objectives.

in missions.lua:
				objective
				{
					override_text mission_text_text_vco_ksl_ort_3_wololo;
					type CONTROL_N_REGIONS_INCLUDING;

change to:

				objective
				{
					override_text mission_text_text_vco_ksl_ort_3_wololo;
					type SCRIPTED;
					script_key vco_dummy;
				}
			
				objective
				{
					type CONTROL_N_REGIONS_INCLUDING;

**Comment by msolefonte** [comment]
Bug ticket created.

**Comment by msolefonte** [comment]
Can be retested.
