### ISSUE TITLE
Fix flavour text for Greasus to be more clear player goals

### ISSUE THREAD

**Issue by OhManTFE** [msolefonte/vco#139]
Route 2 and 3 need this.

**Comment by OhManTFE** [comment]
Need to learn how to embed images properly (defaults to technology icon when it can't find the image I want).

Multiple factions need a pass for this including Greasus, Kostaltyn, Grimgor and probably others.

I can do this all if I get the master packfile but I do still need to learn how to add the military alliance icon and vassal icon to the mod properly (couldn't get it to work last time).

**Comment by msolefonte** [comment]
Moved into beta-6. I think your local list if offseted by one.

**Comment by OhManTFE** [comment]
Implementing the fix has caused another issue where the text shrinks due to the character limit becoming too large? Unsure how exactly the mechanic works (seems to be on a sliding scale) but awaiting guidance on best course of action to either accept the shrunk text as is or stick with the dummy text red font option.

**Comment by msolefonte** [comment]
@OhManTFE Do not close/move tickets please. Only movements you should do:

- Design -> To Do
- To Do -> In progress
- In Progress -> Pull Requested

A ticket is closed when a new version is released. Do not close them earlier. Same with moving them to Ready.

This also goes for you @Mjb141, even if that is not a problem now.

**Comment by msolefonte** [comment]
So what do you want to do? Revert the changes?

**Comment by OhManTFE** [comment]
I already am reverting it on other issues. Basically this issue is redundant and can be deleted with no action required because other issues are covering it.
