### ISSUE TITLE
Throt - Route 1 - Community bug fix collision 

### ISSUE THREAD

**Issue by Mjb141** [msolefonte/vco#142]
![image](https://user-images.githubusercontent.com/46346590/192620371-19227917-3217-4e44-8a77-a3e33f220a30.png)

**Comment by msolefonte** [comment]
We have to try if `CONSTRUCT_N_BUILDINGS_INCLUDING` works well if you use both the old and the new landmark. I know only one is displayed but I am not sure if it actually triggers with just one. We have to know that.

Otherwise we will just add a check to see if the CBF mod is installed and then replace the objective string.

**Comment by msolefonte** [comment]
Can you test this with a trainer? @OhManTFE

**Comment by msolefonte** [comment]
Already contacted the CBFM team to create a fix. I will do it via script.

**Comment by msolefonte** [comment]
Blocked for now because I am working with them to create a compatibility mechanism. They aim to have it released after the next big update of the game, so blocked for now.

**Comment by msolefonte** [comment]
CraigCA — ayer a las 18:02
Lua's not great at that kinda thing, but there's a couple of functions we added to the core library for doing it.

core:is_mod_loaded("mod_name")
^this one searches the list of loaded mods for something matching the string, which is usually good enough, but based on your example might not cut it

core:get_filepaths_from_folder("/script/campaign/whereveryouputthethingie/", "cbfm_enabled")
^this returns a table of all files that match the string filter (2nd parameter), you can then loop through the table with a for loop, and see if any match the file name you're looking for
[18:04]
it may need cbfm_enabled.txt as the string, iirc it's also matching against the extension too. I've only ever used it once myself though, but I think there's an example of it in the endgame manager

**Comment by OhManTFE** [comment]
Is this ever gonna get fixed?

I still think we should just remove it as an objective so people can actually enjoy the Throt campaign, then re-add when the fix finally comes.

**Comment by msolefonte** [comment]
Yup. I already know how to fix it, but not a lot of free time atm

**Comment by OhManTFE** [comment]
Need to swap wh2_main_special_hellpit_pits

with

wh2_main_special_hellpit_pits_moulder_2

in Throt's missions.lua file

(now that the community fix has become official).
