### ISSUE TITLE
Grimgor: Mission aborted reported after completing Route I

### ISSUE THREAD

**Issue by msolefonte** [msolefonte/vco#144]

**Comment by msolefonte** [comment]
@Mjb141 Can you check this one?

**Comment by Mjb141** [comment]
Can't reproduce this. Not downloading Radious to check either, since the reporter has asked about that in the steam comments.

**Comment by msolefonte** [comment]
I got another report via DM which was not using any other mod. I guess we can ask for a savegame/logs if that happens again.
