### ISSUE TITLE
Add Teleport reward to The Drakenholf Conclave

### ISSUE THREAD

**Issue by msolefonte** [msolefonte/vco#145]
Required by #30 

As defined per @OhManTFE:

The Ossified Portal: Triggers a dilemma that allows Mannfred to teleport into Sylvania.
Reward flavour text: Built from the fused remains of a dozen conquered Tomb Kings, this portal allows passage back to your homelands in Sylvania.

# DILEMMA:
PLACEHOLDER TITLE
PLACEHOLDER FLAVOUR TEXT

# BUTTONS:
* Activate Portal - Mannfred will be teleported to Sylvania
* The Time Is Not Right - This dilemma will appear again in 10 turns.
* I Care Not - The portal will permanently close.

# ERROR MESSAGES
* Mannfred cannot teleport while garrisoned in a settlement.
* Mannfred cannot teleport while travelling at sea.
* Mannfred cannot teleport while besieging a settlement.

**Comment by msolefonte** [comment]
Also for ya @Mjb141. I do not think I have enough time for this one. There are some tutorials out there, it is not as complex as it may seem. It is also a good way to introduce you to dilemmas.

**Comment by OhManTFE** [comment]
Can easily push this to another release weeks or months later. 25% campaign movement will help players do the big walk in the meantime until we unlock that Aperture Science Portal Technology!

**Comment by msolefonte** [comment]
Removing the milestone for `beta-6` a sit is not required. I would like it to be there tho.

**Comment by Mjb141** [comment]
Yeah this is brand new to me so chances of it going in `beta-6` are nil. Give them +25% campaign movement range. We can update that at a later date.

**Comment by msolefonte** [comment]
Adding `beta-6` back, because we are not releasing now anyway.
