### ISSUE TITLE
Add script check for the collection of Books of Nagash

### ISSUE THREAD

**Issue by msolefonte** [msolefonte/vco#146]
Required by https://github.com/msolefonte/vco/issues/30

**Comment by Mjb141** [comment]
I can't find a thing about his books in the db. It's allllll Volkmar's book stuff. They must have implemented them in a different way previously.

**Comment by Mjb141** [comment]
They're coded as missions, not as resources.

`missions_tables`: Search for `books_of_nagash_`

Event: https://chadvandy.github.io/tw_modding_resources/WH3/scripting_doc.html#MissionSucceeded
Interface: https://chadvandy.github.io/tw_modding_resources/WH3/scripting_doc.html#CAMPAIGN_MISSION_SCRIPT_INTERFACE

**Comment by Mjb141** [comment]
https://cdn.discordapp.com/attachments/1021682533911511062/1031231256882577458/works1.png

**Comment by msolefonte** [comment]
No PR? Why is this closed without code changes?

**Comment by msolefonte** [comment]
There was a PR but it was not linked. Closed.
