### ISSUE TITLE
Generic `earnXPooledResource(resource, amount)` function needed

### ISSUE THREAD

**Issue by Mjb141** [msolefonte/vco#149]
Many factions have their own pooled resources. Some are spent over time which makes [HAVE_AT_LEAST_X_OF_A_POOLED_RESOURCE](https://tw-modding.com/index.php/Missions/Victory_Conditions#HAVE_AT_LEAST_X_OF_A_POOLED_RESOURCE) a poor objective for them.

A generic function that could accept resource code (e.g. `bst_dread` for Beastmen Dread) and an amount X and return true (they have earned >=X) or false (they have not earned >=X) would be very helpful.

**Comment by msolefonte** [comment]
It is tested by another route automatically so it can be closed directly.
