### ISSUE TITLE
Add an effect for Allegiance Points: +N% with Vampire Coast

### ISSUE THREAD

**Issue by OhManTFE** [msolefonte/vco#152]
## Arkhan the Black Route II Payload

There is no option for Allegiance points for Vampire Coast. Only Vampire Counts.

I would like either:
(a) make a separate one for vampire coast
-or-
(b) modify the vampire count one to also give vampire coast

**Comment by msolefonte** [comment]
@Mjb141 Check this one when able. I think it should be easy to replicate with a global search

**Comment by Mjb141** [comment]
Done https://github.com/msolefonte/vco/commit/a86b2fe28f07f6a02c9fc2e9fed40d61ae5370c8
