### ISSUE TITLE
Listeners file is getting very long already - can we split racial listeners to their own files and lua `include` them into the main file?

### ISSUE THREAD

**Issue by Mjb141** [msolefonte/vco#158]

**Comment by msolefonte** [comment]
Closed as it won't be done by now. Maybe in the future. Reasons provinded in an individual chat:

> Considering the code out there, including CA's, I think it is fine for now. Main problem with splitting per race is that we will have 24 files with 50 lines. I prefer one with 800-1000 lines as long as it is properly sorted

> In any case, a refactor on this area is something we can do over time. It will not be less of a problem if we do it now than if we do it in some months

> The average CA script has over a thousand lines and uses no function or just a few. We are grand for now
