### ISSUE TITLE
Fix Church building objective in Kostaltyn Route 3

### ISSUE THREAD

**Issue by OhManTFE** [msolefonte/vco#163]
This is my fault because I said build 6 Orthodoxy Churches.

But there are actually two different buildings with identical name Orthodoxy Church.

wh3_main_ksl_city_temple_1
wh3_main_ksl_city_temple_2
wh3_main_ksl_city_temple_3
wh3_main_ksl_city_temple_4
^ These ones are difficult you can only get them in major cities which you only have 3. Then you would need to capture 3 more capitals like Hell Pit, Altdorf, Couronne, something like that. Pretty difficult.

I meant it to be the regular churches which is this;

wh3_main_ksl_gold_1
wh3_main_ksl_gold_2
wh3_main_ksl_gold_3

6 of these Orthodoxy Churches:
wh3_main_ksl_gold_3
will be a more reasonable objective.

**Comment by msolefonte** [comment]
I do not think it is that bad. You still have to capture Altdorf, Marienburg, Middenheim and Castle Drakenhof. It is logical to build the churches on these cities if you want to convert them.

**Comment by OhManTFE** [comment]
I just ran a test after reading a Steam comment on the issue.

I was mistaken. Though capital cities are level 5, they do not allow the construction of the tier 4 churches, only the tier three ones.

So as it stands right now, this objective is impossible to complete.

We HAVE to change it to wh3_main_ksl_gold_3

**Comment by msolefonte** [comment]
I am thinking of releasing this as a hotfix. Do you agree?
