### ISSUE TITLE
Replace Goldtooth's CONTROL_N_REGIONS_INCLUDING key with CONTROL_N_REGIONS_FROM

### ISSUE THREAD

**Issue by msolefonte** [msolefonte/vco#172]
The code does not match the docs. Easy fix.

**Comment by OhManTFE** [comment]
The problem is I still did the overwrite text for these on Route II. This overwrite text now needs to be deleted.

					override_text mission_text_text_vco_ogr_gre_2_at_least_6_provinces;

^ delete this in the .lua file, and it's also present in text>db

**Comment by msolefonte** [comment]
Bug ticket created.

**Comment by msolefonte** [comment]
Can be retested.
