### ISSUE TITLE
Find an alternative to Throt's RAZE_OR_SACK_N_DIFFERENT_SETTLEMENTS_INCLUDING key

### ISSUE THREAD

**Issue by msolefonte** [msolefonte/vco#173]
We have to find an alternative, because RAZE_OR_SACK_N_DIFFERENT_SETTLEMENTS_FROM does not exist. Redesign the route and update code and docs.

**Comment by OhManTFE** [comment]
My suggestion is change to occupy.

CONTROL_N_REGIONS_FROM

Easy fix.

**Comment by Mjb141** [comment]
I like this fix idea. I'm going to make that change and test it.

**Comment by Mjb141** [comment]
That produces this which makes no sense:


![Image](https://user-images.githubusercontent.com/46346590/194728161-a2904b1f-d225-4e63-8d4b-90804acb9233.png)

Do we need to pick four settlements here @OhManTFE ?

**Comment by OhManTFE** [comment]
No, that will work.

It's just unfortunate the text doesn't reflect that very well. I have been making a habit of creating overwrite text for these situations. So it instead says:

Control at least 4 of the following regions either by direct ownership or through [[img:icon_vassal]][[/img]]vassals and [[img:icon_military_alliance]][[/img]]military allies:

**Comment by Mjb141** [comment]
> It's just unfortunate the text doesn't reflect that very well. I have been making a habit of creating overwrite text for these situations. So it instead says:
> 
> Control at least 4 of the following regions either by direct ownership or through [[img:icon_vassal]][[/img]]vassals and [[img:icon_military_alliance]][[/img]]military allies:

I've done this in the fix branch: https://github.com/msolefonte/vco/pull/176/files

**Comment by msolefonte** [comment]
I would leave it there as it is just an incompatibility with another mod. It should be fixed soon anyway.
