### ISSUE TITLE
Skarbrand Taurox (Beta 9) Issues

### ISSUE THREAD

**Issue by OhManTFE** [msolefonte/vco#266]
@Mjb141 

TAUROX
* Due to CA fail, Taurox's unique quest is not the final quest in his campaign, it's the generic one. So this:
**wh3_main_ie_qb_bst_final_battle_taurox**
needs to change to this:
**wh_dlc03_qb_bst_the_final_battle**
Otherwise, the route is unfinishable.

* Taurox' Khorne corruption reward for route 1 is being negated by a -5 factionwide effect. Please increase the two values of 8 and 5 to 15 and 10.

SKARBRAND
* Skarbrand's skull script is not working, thus I cannot test it.
Skarbrand's new payloads:
* Great Game Route:
wh3_main_effect_region_chance_to_spread_to_ruin_source
province_to_province_own
+15% chance to automatically colonise ruined regions in province at turn start

* Blood Route:
wh3_main_effect_kho_spawned_armies_melee_attack_mod
+5% Melee attack for Blood Hosts
faction_to_force_own

* Skull Route:
wh3_main_effect_force_stat_range_kho_skullcannon
Range +25% for Skullcannons
faction_to_force_own
wh3_main_effect_force_stat_charge_bonus_add_kho_skullcrusher
Charge bonus: +8% for Skullcrushers of Khorne units
faction_to_force_own

**Comment by Mjb141** [comment]
@OhManTFE I need logs for the skull script, rest is done.

**Comment by OhManTFE** [comment]
Logs on discord
