### ISSUE TITLE
Update RoC docs

### ISSUE THREAD

**Issue by msolefonte** [msolefonte/vco#279]

**Comment by OhManTFE** [comment]
# Kislev

## Tzarina - The Ice Court

* **Route I - There Can Only Be One**
  * Control the following 3 settlements:
    * Erengrad, Praag, Kislev
  * At the start of your turn, have at least 600 Supporters
  * **Reward**:
    * _The Red Room_: Control +2 (all characters), Hero action success chance +30%, Campaign line of signt: +100%
    * _United Against Chaos_: Leadership +10 when fighting Forces of Chaos, Experience gain for units: +50% when fighting against Forces of Chaos

* **Route II - From Kislev With Love**
  * Destroy factions:
    * Legion of Chaos, Clan Moulder, Legion of the Gorequeen, The Drakenhof Conclave
  * **Reward**:
    * _Frozen Heart_: Cooldown -10% to Lore of Ice spells, Miscast base chance -30% when fightijng against Forces of Chaos, Passive ability: The Chilling Aura

* **Route III - Defenders of the World**
  * Occupy, loot, raze or sack 32 different settlements.
  * Raze or sack 5 settlements belonging to the following race:
    * Norsca, Warriors of Chaos
  * **Reward**:
    * _A Call For Aid_: A dilemma will offer a choice between powerful rewards!
    * _The Northern Crusades_: Diplomacy +40 for Bretonnians, Recruit rank +3, Speed +10% and Charge bonus +10% for Kossovite Dervishes, Winged Lancers and Gryphon Legion units
    * _The Slayers Come_: Diplomacy +40 for Dwarfs, Enables Liquid Fortification for Tzar Guard units, Melee attack: +10 for Tzar Guard units, Unlocks Dwarf units: Slayers and Giant Slayers
    * _Shipments from Nuln_: Diplomacy +40 for The Empire, Unlocks Empire units: Mortars and Great Cannons, Range: +20% for Kislev units, Missile strength: +10% for Kossars
    * _The Conclave of Light_: Diplomacy +40 for High Elves, Winds of Magic power reserve capacity: +10, Winds of Magic cost: -10% for all spells, Magic item drop chance: +20% (all characters)

## Kostaltyn - The Great Orthodoxy

* **Route I - There Can Only Be One**
  * Control the following 3 settlements:
    * Erengrad, Praag, Kislev
  * At the start of your turn, have at least 600 Supporters
  * **Reward**:
    * _Dethroned_: Motherland invocation cost: -25%, Growth: +60, Control: +4

* **Route II - The Last Bastion**
  * Destroy factions:
    * Clan Moulder, Puppets of Misrule, Wintertooth, Legion of Chaos
  * **Reward**:
    * _Ice Court Defectors_: Barrier hit points: +600 for all units when defending settlements, campaign movement range: -20% for enemy armies starting their turns in player-controlled regions

* **Route III - Wololo!**
  * Control settlements:
    * Altdorf, Marienburg, Middenheim, Castle Drakenhof
  * Destroy factions:
    * Reikland, Marienburg, Middenland, The Drakenhof Conclave
  * **Reward**:
    * _The Scourge of Altdorf_: Luminark of Hysh
    * _Conversion of Marienburg_: Income from Ports: +30%
    * _The Syncretism of Middenheim_: Melee defence: +6 when under siege
    * _The Cleansing of Drakenhof_: Corruption -2

## Boris - Ursun Revivalists

* **Route I - Doomslayer**
  * Destroy factions:
    * Legion of the Gorequeen
  * Control at least 2 of the following regions:
    * Palace of Princes, Infernius, The Sunken Sewers, The Volary
  * **Reward**:
    * _Rip & Tear_: Speed: +6% (Lord's army), Weapon strength: +8% (Lord's army), Ward save: 5% when fighting against Forces of Chaos, Experience gain for units: +20% when fighting against Forces of Chaos

* **Route II - The Old Frontier**
  * Control the following 3 provinces:
    * Zorn Uzkul, The High Pass, Road of Skulls
  * Raze or conquer the following settlements:
    * Zharr Naggrund, The Silver Pinnacle
  * **Reward**:
    * _Kislev Ascendant_: Construction cost: -15% for all buildings, Income from post-battle loot: +10%, Ward save: 5% when fighting against Greenskins, Ogres and Skaven

* **Route III - Blood in the Snow**
  * Control the following 3 settlements directly or diplomatically:
    * Erengrad, Praag, Kislev
  * At the start of your turn, have at least 600 Supporters
  * **Reward**:
    * _Supply Trains_: Vigour loss reduction: -20%, Recruitment cost: -10%, Global recruitment duration: -1 turn for all units, Ammunition: 20% for missile infantry units

__________________________________________________

# Cathay

## Miao Ying - The Northern Provinces

* **Route I - In Harmony**
  * Maintain control of the following provinces:
    * Gunpowder Road, Lands of Stone and Steel, Imperial Road, Forests of the Moon, Celestial Riverlands, Broken Lands of Tian Li, Wastelands of Jinshen, Warpstone Desert
  * **Reward**:
    * _An Empire United_: Growth: +60, Control: +4, Bound spell: Ancestral Warriors (faction leader)

* **Route II - Cold and Aloof**
  * Control the following 3 settlements:
    * Snake Gate, Dragon Gate, Turtle Gate
  * Construct the Ninth Wall landmark
  * Destroy the following factions:
    * The Ecstatic Legions, Oracles of Tzeentch, Clan Eshin
  * **Reward**:
    * _Unreachable_: Barrier hit points: +600 for all units when defending settlements, Melee defence: +6 when defending

* **Route III - The Northern Expedition**
  * Search the following Dark Fortresses for the Old One Relic:
    * Red Fortress, The Volary, Zerulous, City of Splinters, The Gallows Tree, The Writhing Fortress, The Sunken Sewers, Blood Haven, The Crystal Spires, Black Rock, Infernius, The Silvered Tower of Sorcerers, The Shifting Monolith, The Palace of Ruin
  * **Reward**:
    * _Upgraded Wu Xing Compass_: Wu Xing Compass cooldown: -1 turns, Enables Burning Alignment for Wu Xing War Compasses, Corruption -8 (all provinces)

## Zhao Ming - The Western Provinces

* **Route I - Iron into Gold**
  * Complete the Ivory Road with at least 9 caravans.
  * Trade a minimum of 13140 goods with the west.
  * Control the following settlement:
    * Shang-Yang
  * Construct The Great Embassy landmark
  * **Reward**:
    * _Global Influence_: Diplomatic relations: +40 with High Elves, Bretonnia, Dwarfs, The Empire

* **Route II - All That Glitters Is Not Gold**
  * Raze or conquer the following settlements:
    * Seep-Gore, Hell Pit, Castle Drakenhof, Castle Drachenfels, Crookback Mountain
  * **Reward**:
    * _The Warpstone Hoard_: Spell Flensing Ruin for Zhao Ming (cooldown and mana cost reduced), Skaven corruption +13 for Zhao Ming, Army ability: Warpstone Doomrocket (one use per battle (all armies)

* **Route III - Don't Tread on Ming**
  * Maintain control of the following provinces:
    * Ivory Road, Wyrm Pass, Ice Pass
  * Raze or conquer the following settlements:
    * Black Fortress
  * **Reward**:
    * _Safe Roads_: Maximum cargo capacity: +100% for caravans, Income from trade tariffs: +60%

__________________________________________________

# Ogre Kingdoms

## Greasus Goldtooth - Goldtooth Tribe

* **Route I - Too Rich to Walk**
  * Have a gross income of 25,000
  * Construct the 2 following buildings:
    * Mint (Gold Mine), Big Gem Mine (Diamond Mine)
  * **Reward**:
    * _Hoardmaster_: Diplomatic relations: +30 with all factions, Global recruitment capacity: +2

* **Route II - Overtyrant's Reign**
  * Maintain control of the following provinces:
    * Ivory Road, Mountains of Mourn, Wyrm Pass, Ice Pass, Ancient Giant Lands, Bone Road, Gash Kadrak, Path to the East
  * Construct the following 5 landmarks:
    * Goldtooth's Toll Gate, The Fire Mouth, Karak Azorn Great Hall, Abandoned Sky-Titan Hold, Challenge Stone Bulge
  * **Reward**:
    * _Hell on Wheels_: Charge Bonus: +20%, Speed: +35% for Greasus Goldtooth

* **Route III - Drakecrush**
  * Maintain control of the following provinces:
    * Imperial Road, Forests of the Moon
  * **Reward**:
    * _Subservient Cathayans_: Magic item drop chance: +10% (all characters), Camp limit: +2, Income from trade: +20% for every ally


## Skrag the Slaughterer - Disciples of the Maw

* **Route I - Pilgrim of the Maw**
  * Offer a total of 200 Meat to the Great Maw
  * Win the Cauldron of the Great Maw quest battle
  * Control the following settlement:
    * Yhetee Peak
  * **Reward**:
    * _Journey's End_: Camp limit: +2, Income from post-battle loot: +10%, Cooldown: -20% to The Maw spell, Winds of Magic cost: -10 for The Maw spell

* **Route II - The Age of Ogres**
  * Destroy factions:
    * Reikland, Middenland, Marienburg
  * Raze or sack 15 Empire settlements
  * **Reward**:
    * _The Ogre Empire_: Camp growth: +10 for all camps, Camp limit: +2, Speed: +20% (faction leader), Passive ability: Bloodgreed (Lord's army)

* **Route III - Hunger for Power**
  * Control at least 3 of the following regions:
    * Castle Drakenhof, Karak Kadrin, Zhufbar, Kislev, Praag, Erengrad
  * Construct the Gorger Haunt landmark
  * **Reward**:
    * _Well-Fed_: Camp limit: +2, Hero recruit rank: +3 for Butchers, Armour: +5 and Charge bonus: +10 for Sabre tusk packs, Stonehorns, Gorgers and Giant units

__________________________________________________

# Daemons of Chaos

## Godslayer - Legion of Chaos

* **Route I - Ascension**
  * Occupy, loot, raze or sack 35 different settlements.
  * Ascend in service to any Chaos God, or as an Undivided champion of all.
  * **Reward**:
    * _Worldslayer_: Campaign movement range: +80% after winning a battle (all armies), Upkeep: -20% for Daemon units

* **Route II - Witness Me!**
   * Raze or conquer the following settlements:
    * Altdorf, Middenheim, Karak Kadrin, Wei-Jin, Nan-Gau
  * **Reward**:
    * _Everchosen_: Diplomatic relations: +20 with Warriors of Chaos, Daemons of Chaos, Beastmen and Norsca, Passive ability: The Crown of Domination (faction leader)

* **Route III - Succeeding You**
  * Destroy factions:
    * The Ice Court, The Great Orthodoxy
  * Raze or conquer the following settlements:
    * Praag, Erengrad, Kislev
  * **Reward**:
    * _God of Kislev_: Hit Points: +30%, Armour: +30, Base weapon damage: +30, Barrier hit points: +300 for faction leader
    * _Frostmourne_: Causes attrition to enemy armies within your territory, Spell unlocked for faction leader: Blizzard (cooldown -50%, mana cost -10)

# Khorne

## Skarbrand - Exiles of Khorne

* **Route I - The Great Game**
  * Ascend in the Great Game by spreading your corruption over 100 regions
  * Win the Slaughter & Carnage quest battle
  * Reach rank 40 with Skarbrand
  * **Reward**:
    * _Khorne Ascendant_: Casualty replenishment rate: +8%, Upkeep: -25% for Khorne daemon units, +15% chance to automatically colonise ruined regions in province at turn start

* **Route II - Blood for the Blood God**
  * Occupy, loot, raze or sack 32 different settlements.
   * Raze or conquer the following settlements:
    * Castle Drakenhof, The Silver Pinnacle
  * Destroy factions:
    * The Drakenhof Conclave
  * **Reward**:
    * _The Reaping_: Blood Hosts: Gauranteed chance of receiving +1 Bloodthirsters units on creation, Blood Hosts +1 turns to Bloodthirst attrition immunity from battles, Melee attack: +5% for all units in Blood Hosts, Melee attack: +8 for Bloodletters, Exalted Bloodletters and Bloodcrushers

* **Route III - Skulls for the Skull Throne**
  * At the start of your turn, have at least 16,000 skulls
  * Destroy factions:
    * Seducers of Slaanesh, The Ecstatic Legions
  * Raze or sack 8 settlements belonging to Slaanesh races
  * **Reward**:
    * _Skulls of the Slain_: Skulls collected from skull piles: +50%, Skulls gained from kills: +50%, Charge bonus: +8 for Skullcrushers, Range: +25% for Skullcannons


# Nurgle

## Ku'gath - Poxmakers of Nurgle

* **Route I - The Great Game**
  * Ascend in the Great Game by spreading your corruption over 100 regions
  * At the start of your turn, have at least 2000 Infections
  * **Reward**:
    * _Nurgle Ascendant_: Hero capacity: +5 for Cultists, Nurgle corruption in adjacent provinces: +15, Chance of a plague spreading: +10%

* **Route II - Toil & Trouble**
  * Control at least 3 of the following regions:
    * Wei-Jin, Nan-Gau, Po Mei, Zhanshi, Shang-Wu, Hanyu Port
  * Raze or conquer the following settlements:
    * Kislev, Erengrad, Praag
  * **Reward**:
    * _Zin-Fa the Ever-Pustulent_: Growth per region: +5 after winning a battle, Missile resistance: +10% when fighting against Cathay
    * _Kislevian Gout_: Infection cost: -20%, Melee attack: +5 when fighting against men

* **Route III - Death to the Dwarfs!**
  * Raze or conquer the following settlements:
    * Karak Dum, Kraka Drak, Karak Azorn, Zhufbar, Karak Kadrin, Zharr Naggrund
  * Destroy factions:
    * Karak Kadrin
  * **Reward**:
    * _The Urfather's Forgiveness_: Passive ability: Acid Ichor, Speed +10%, Missile strength: +10% (faction leader)
    * _River Ruin Pathogen_: Melee defence: +5, Armour: +10 for Nurglings units

# Slaanesh

## N'Kari - Seducers of Slaanesh

* **Route I - The Great Game**
  * Ascend in the Great Game by spreading your corruption over 100 regions
  * **Reward**:
    * _Slaanesh Ascendant_: Slaanesh corruption in adjacent provinces: +4, Slaanesh corruption: +6, Increases experience gain: +10% for units when fighting against the Forces of Order
    * _All The World's A Stage_: Recruit rank: +3 for Daemonettes of Slaanesh and Exalted Daemonettes of Slaanesh units, Weapon strength: +5% for Daemonettes of Slaanesh, Exalted Daemonettes of Slaanesh, Chaos Warriors of Slaanesh and Marauders of Slaanesh units

* **Route II - Paradise Lost**
  * Spread at least 40 Gifts of Slaanesh
  * Establish at least 20 Chaos Cults
  * **Reward**:
    * _Cult Following_: Hero recruit rank: +5, Summon Disciple Army size: +20%, Hero action cost: -30%, Hero action success chance: +20%

* **Route III - Wrath & Desire**
  * Destroy factions:
    * Exiles of Khorne
  * Control at least 6 of the following 9 regions:
    * Infernius, The Writhing Fortress, Lair of the Troll King, Kislev, Laurelorn Forest, Altdorf, Middenheim, Marienburg, Nuln
  * **Reward**:
    * _Bound to the Blade_: Weapon strength: +10% for N'Kari, Leadership: +10 when fighting against Khornate factions
    * _Sweet Surrender_: Allegiance points gained: +25%, Devotees: +40 per turn, Tribute from vassals: +100%


# Tzeentch

## Kairos Fateweaver - Oracles of Tzeentch

* **Route I - The Great Game**
  * Ascend in the Great Game by spreading your corruption over 100 regions
  * At the start of your turn, have at least 2000 Grimoires
  * **Reward**:
    * _Tzeentch Ascendant_: Tzeentch corruption in adjacent provinces: +15, Hero and Lord recruit rank: +5, Cooldown: -15% to Lore of Tzeentch and Metal spells

* **Route II - Visions of the Past**
  * Destroy factions:
    * Poxmakers of Nurgle
  * Raze or conquer the following settlement:
    * Tancred Castle
  * **Reward**:
    * _The Fateweaver's Vengeance_: Chance of a plague spreading: -10%, Growth: +10, Changing of the Ways cost: -10%
    * _The Twelve Artefacts of Gilles le Breton_: Ability: Chalice of Potions, Charmed Shield for Kairos

* **Route III - Visions of the Future**
  * Destroy factions:
    * The Northern Provinces, The Western Provinces
  * Raze or conquer the following settlement:
    * Wei-Jin
  * **Reward**:
    * _The Wu Xing Compass_: Causes attrition to enemy armies within your territory, Chance of Winds of Magic increasing in strength when changing: +15%, Army ability: Summoned from Beyond
