### ISSUE TITLE
TMB - Followers of Nagash

### ISSUE THREAD

**Issue by OhManTFE** [msolefonte/vco#29]
# Tomb Kings

## ARKHAN: Followers of Nagash

* **Route I - Thy Kingdom Come**
  * Arkhan has feigned obedience to Settra for long enough. The time has come to march out and retake the ancient lands of his master, the Great Necromancer Nagash.
  * Occupy at least 6 provinces:
    * Land of Assassins, Coast of Araby, Great Desert of Araby, The Cracked Land, Great Mortis Delta, Land of the Dead, Shifting Sands, Land of the Dervishes
  * Destroy faction:
    * Khemri
  * **Reward**:
    * _Thy Will Be Done_: Recruitment rank +4, Unit capacity: %+4\nTomb Guard\nTomb Guard (Halberds)\nSkeleton Chariot\nSkeleton Archer Chariot
_Reward flavour text:_ Arkhan journeys across the dunes, enslaving Tomb Kings from every dynasty and binding their legions to his will. Those who resist are destroyed utterly - their powdered bones lost to the sands of time forevermore.

* **Route II - Born to Serve**
  * The vampires did not drink from the Elixir of Life as Arkhan did, but from a lesser, corrupted version that cursed them with unlife. They are forever bound to the will of Nagash, and as his foremost servant, Arkhan can command them just as easily.
  * Occupy at least 4 settlements:
    * Galleon's Graveyard, The Awakening, Lahmia, Castle Drakenhof, Silver Pinnacle, Blackstone Post, Haunted Forest
  * **Reward**:
    * _Know Your Place_: Vampire Count and Vampire Coast allegiance +100%, Vampiric corruption +5 (factionwide), Vampiric corruption adjacent provinces +5 (factionwide)
_Reward flavour text:_ These bloodthirsty creatures will make fine foot soldiers in the wars to come. Let their blight curse the lands.

* **Route III - Faithful Servant**
  * The portents are troubled. Daemons roam the earth. Ancient empires crumble before the coming of Chaos. Preparations must be made for the Great Necromancer's return.
  * Occupy settlements:
    * Black Tower of Arkhan, Black Pyramid, Nagashizzar
  * Collect all Books of Nagash
  * **Reward**:
    * _Mortarch of Sacrament_: Army capacity +3, Lord + hero recruit rank +5, Rite cooldown reduction -25%
_Reward flavour text:_ Foremost of the Dark Lords, Arkhan heralds in a new age of death and despair.

**Comment by OhManTFE** [comment]
test

**Comment by msolefonte** [comment]
Just some notes. Occupy settlements and dummies can be merged.

I am also not sure with rewards, they feel like too much, but I do not play TK at all so your call.

**Comment by msolefonte** [comment]
No scripts required?

**Comment by OhManTFE** [comment]
Rite cooldown reduction -25% may be beyond my ability. Alternatively, we could remove it as a reward entirely if we're lazy.

**Comment by OhManTFE** [comment]
My dummy texts for Arkhan and Mannfred still have the red crossout. That is because when I coded them and sent them the discovery of being able to remove the red tick crossout hadn't happened yet.

In future packfiles I will make sure to use this new discovery.

**Comment by OhManTFE** [comment]
In text>db> vco_mission_text.loc Change this text:

mission_text_text_vco_tmb_ark_2_born_to_serve_region_overwrite	Occupy the following provinces:

Becomes:
Control at least 4 of the following regions either by direct ownership or through [[img:icon_vassal]][[/img]]vassals and [[img:icon_military_alliance]][[/img]]military allies:

In the script, missions.lua, change route 2 from:

					override_text mission_text_text_vco_tmb_ark_2_born_to_serve_region_overwrite;
					type CONTROL_N_REGIONS_INCLUDING;
					total 4;

					region wh3_main_combi_region_the_galleons_graveyard;
					region wh3_main_combi_region_the_awakening;
					region wh3_main_combi_region_lahmia;
					region wh3_main_combi_region_castle_drakenhof;
					region wh3_main_combi_region_silver_pinnacle;
					region wh3_main_combi_region_blackstone_post;
					region wh3_main_combi_region_the_haunted_forest;      

to 

					type CONTROL_N_REGIONS_FROM;

**Comment by OhManTFE** [comment]
Route 2 payload was supposed to be updated to include Allegiance points gained: +100% for alliances with Vampire Counts AND Vampire Coast, but this is not visible on the objective screen.

I see it in the db>effect_bundles_to_effects_junctions_tables section:
vco_victory_payload_tmb_ark_2_born_to_serve	vco_tmb_arkhan_allegiance_points_mod_vampire_coast	faction_to_faction_own_unseen	100.0000	start_turn_completed

But as per this screenshot you can see it isn't appearing in-game:
https://i.imgur.com/BztHcC7.png

**Comment by msolefonte** [comment]
Can be retested.

**Comment by OhManTFE** [comment]
![deleteconsistentcy](https://user-images.githubusercontent.com/112160524/197236015-03804b53-f137-471f-9519-2a9527475262.png)

https://i.imgur.com/l7p63qN.png

In text>db>vco_effects.loc can we delete the word "units" for consistency + clarity?

effects_description_vco_tmb_arkhan_allegiance_points_mod_vampire_coast
Allegiance points gained: %+n% for alliances with Vampire Coast units

becomes:
effects_description_vco_tmb_arkhan_allegiance_points_mod_vampire_coast
Allegiance points gained: %+n% for alliances with Vampire Coast
