### ISSUE TITLE
VMP - The Drakenholf Conclave

### ISSUE THREAD

**Issue by OhManTFE** [msolefonte/vco#30]
```markdown
# Vampire Counts

## MANNFRED: Drakenhof Conclave

* **Route I - The Restless Dunes**
  * The shifting sands of Nehekhara hide many long lost tombs filled with powerful magical artifacts that Mannfred desires. They also hide many foes who would see him undone. They will find only death and an unlife of eternal servitude in these dunes.
  * Destroy factions:
    * Khemri, Cult of Sigmar, Chevaliers de Lyonesse
  * Control provinces:
    * Shifting Sands, Land of the Dervishes, The Cracked Land, Land of the Dead, Coast of Araby, Land of Assassins, Great Desert of Araby
  * **Reward**:
    * _The Ossified Portal_: Creates a dilemma
_Reward flavour text:_ Built from the fused remains of a dozen conquered Tomb Kings, this portal allows passage back to your homelands in Sylvania.
    * _The Ossified Monolith_: Campaign movement range +10% for all armies, +20 diplomatic relations with Vampire Counts
_Reward flavour text:_ Built from the fused remains of a dozen conquered Tomb Kings, this monolith throbs with unholy power.

* **Route II - Reclaiming the Throne**
  * The time has come to return to Sylvania and reclaim the von Carstein's ancestral citadel: Castle Drakenhof. In his private chambers in the uppermost tower Mannfred can continue to study the Books of Nagash he has found thus far. But first, Vlad and Isabella must be convinced to recognise his supremacy, or else be staked through the heart and left out for dawn's light to take them.
  * Destroy factions:
    * Sylvania
  * Control province:
    * Northern Sylvania, Southern Sylvania
  * Construct landmark:
    * Malovelent Museum
  * **Reward**:
    * _Return of the Count_: , Blood Kiss +3, +20 Weapon Strength for armies fighting against The Empire, Kislev.
_Reward flavour text:_ "This land is my home, my birthright. The wind and rain are my allies. The trees and stones are my foot soldiers. The very earth will rise up against you should you try to take it from me. And my people will feast on your bones."

* **Route III - Death Comes For All**
  * Mannfred means to marshal every last vestige of the Great Necromancer's power and launch an unholy assault upon the Empire. The reign of the Midnight Aristocracy is nigh...
  * Occupy regions:
    * Black Pyramid of Nagash, Nagashizzar, Altdorf
  * Collect the Eight Books of Nagash
  * **Reward**:
    * _The Mortarch of Night_: Recruitment duration -1 turn for all units (minimum 1), Recruitment cost: -20% (all armies), Cooldown -20% to spells (all armies)
_Reward flavour text:_ "Nagash was a fool, too weak to see his dreams realised. I will build an empire of death atop his broken legacy."
    * _The Dread Emperor_: Weapon strength +20%, Ward save +20% for Mannfred
_Reward flavour text:_ From Nuln to Nordland, all pay the blood tithe and live only to serve the von Carsteins.

**Comment by msolefonte** [comment]
Scripts required:

- CHECK Collect the Eight Books of Nagash

**Comment by OhManTFE** [comment]
The Ossified Portal: Generates a dilemma.
Reward flavour text: Built from the fused remains of a dozen conquered Tomb Kings, this portal allows passage back to your homelands in Sylvania.

# DILEMMA:
PLACEHOLDER TITLE
PLACEHOLDER FLAVOUR TEXT

# BUTTONS:
* Activate Portal - Mannfred will be teleported to Sylvania
* The Time Is Not Right - This dilemma will appear again in 10 turns.
* I Care Not - The portal will permanently close.

# ERROR MESSAGES
* Mannfred cannot teleport while garrisoned in a settlement.
* Mannfred cannot teleport while travelling at sea.
* Mannfred cannot teleport while besieging a settlement.

**Comment by OhManTFE** [comment]
@msolefonte 

Need to delete the province override text in Route I.

Route III: Collect all the Books of Nagash is ticked on turn 1 because script_key is vco_dummy;

@Mjb141 Do you still need to make Mannfred's book script, like you did for Arkhan?

**Comment by Mjb141** [comment]
I didn't even realise Mannfred needed a script, his books are available as a pooled resource, don't we just use that?

**Comment by msolefonte** [comment]
Two new bug tickets created to close this one.

**Comment by msolefonte** [comment]
Can be retested.

**Comment by OhManTFE** [comment]
![noportal](https://user-images.githubusercontent.com/112160524/197237838-9f183b1b-73fb-41bd-8ee0-c823c636b0d5.png)

There's currently no indication to the player that a portal to Sylvania dilemma will appear on this objective.

Solutions, (1) make a custom reward under the first payload, (2) make a second payload:
TITLE: Soulgate
TEXT: A portal to Sylvania will become available to Mannfred's army.
ICON: souls.png (attached)

![souls](https://user-images.githubusercontent.com/112160524/197239843-75c994d3-9239-4106-a892-1268811cc9fa.png)

**Comment by OhManTFE** [comment]
![first book didnt work](https://user-images.githubusercontent.com/112160524/197241409-ce87967d-39bf-4c08-ba8d-93e71857c54e.png)

Mannfred Book of Nagsh not working still. Lognotes attached.
[script_log_221022_0149.txt](https://github.com/msolefonte/vco/files/9840720/script_log_221022_0149.txt)
