### ISSUE TITLE
SKV - Clan Moulder

### ISSUE THREAD

**Issue by msolefonte** [msolefonte/vco#42]

**Comment by OhManTFE** [comment]
## Throt the Unclean - Clan Moulder

* **Route I - **
  * OBJECTIVE FLAVOUR TEXT
  * Unlock all Infantry Augments and Monster Augments
  * Build landmark: Depths of the Pit
    * _REWARD TITLE_: Research rate +50%, Growth Juice per turn +40
_Reward flavour text:_ 

* **Route II - The Vermintide Comes**
  * OBJECTIVE FLAVOUR TEXT
  * Destroy factions: 
    * The Ice Court, The Great Orthodoxy
  * Occupy/Raze at least 4 settlements:
    * Kislev, Altdorf, Middenheim, Brass Keep, Gryphon Wood, Castle Drakenhof, Karak Kadrin
    * _REWARD TITLE_: Food generated: X per turn, recruit rank +X for mutants
_Reward flavour text:_ 

* **Route III - Harvest Chaos Specimens (tbd)**
  * OBJECTIVE FLAVOUR TEXT
  * Destroy/ally factions: The Ecstatic Legions, Wintertooth, Hag Graef, Ursun Revivalists, Legion of Chaos, Warhost of the Apocalypse
    * _REWARD TITLE_: Mutagens per turn X, weapon strength +10% for mutants or casualty replenishment 10% for mutants
_Reward flavour text:_

**Comment by MichaelBrown08** [comment]
Lot of placeholder text here @OhManTFE - I've added it all as PLACEHOLDER, will wait for an update on text. If you want any assistance let me know!

**Comment by msolefonte** [comment]
Good stuff, but I do not like the first one. The idea of routes is that each one of them has to work as an independent campaign. You can complete them all in a row, but without any particular order.

Having the first route named "Prepare for war!", makes me feel it is a preparation for the other routes. It should be more self-contained.

I think something like "Completeing your experiments" or "Find the perfect specimen" can have the same objectives/rewards and yet be more self-contained.
