### ISSUE TITLE
EMP - The Cult of Sigmar

### ISSUE THREAD

**Issue by OhManTFE** [msolefonte/vco#44]
## VOLKMAR: The Cult of Sigmar
Route I - Destroy Arkhan, Settra, Mannfred, Raze Black Pyramid
Route II - Destroy all Books of Nagash
Route III - Revenge on Chaos - defeat Archaon & Be'lakor

**Comment by Mjb141** [comment]
"Also, since CA havent done it for now, could you change the victory conditions of Volkmar the Grim so that insead of the empire, you have to controll the southern realms through war or allies ?"
