### ISSUE TITLE
SKV - Clan Mors

### ISSUE THREAD

**Issue by OhManTFE** [msolefonte/vco#46]
## QUEEK - Clan Mors
Route I - Recapture Karak Eight Peaks, destroy Belegar & Skarsnik
Route II - A New Trophy Rack - collect heads of Settra, Skarbrand, etc.
Route III - Overthrow Skavenblight - Clan Mors reigns

**Comment by msolefonte** [comment]
Just pointing out for Warhammer 2, I had a timeout for K8P routes so you have some sense of preasure:
- Take control of Karak Eight Peaks
- Do it in less than 75 turns

**Comment by OhManTFE** [comment]
A timeout is unprecedented. My experience is needless time pressures forcing players to stop going at their own pace is never going to add to player enjoyment, only remove it. In fact that was a large complaint of the Realms of Chaos campaign.

The other problem with it is it's impossible to balance without difficulty scaling. For a easy difficulty player, is the time pressure trivial and may as well not even be there? For a legendary difficulty player, does the time pressure make the objective actually impossible to complete? I think it's a problematic and unfun objective IMO.

It would make a lot more sense as an optional submod for players seeking a greater challenge. Even then you'd want a way for it to be tied to the campaign difficulty.

**Comment by msolefonte** [comment]
It was like that for years in Warhammer II and nobody complained about difficulty. I also liked the preassure for just one campaign, it gives you a different experience. You could still win by completing the other routes. 

Either take control of the place in less than 75 turns (route 1), or kill those that want to achieve the same (route 2). You win the race or you cheat it. I liked it, and again, it was well received. If you want to balance it differently, though, I will be open to it.

**Comment by msolefonte** [comment]
Queek, Belegar and Skarsnik. They all got the very same routes I and II in Warhammer II. You win the race or you cheat it.
