### ISSUE TITLE
SLA - Seducers of Slaanesh

### ISSUE THREAD

**Issue by msolefonte** [msolefonte/vco#49]
# Slaanesh - REALM OF CHAOS

## N'Kari - Seducers of Slaanesh

* **Route I - The Great Game**
  * Though Slaanesh is presently the least of the four great Ruinous Powers, his brothers secretly fear him, for he feeds on humanity's darkest urges, a source of power that they cannot hope to match. Let the lands of the mortal world be submerged beneath a writhing, twitching blanket of sin.
  * Achieve the highest corruption in a minimum of 100 regions
  * **Reward**:
    * _Slaanesh Ascendant_: Allegiance points gained for all factions: +25%, tribute from vassals +100%, Devotees per turn +40
Alternatives: could also buff things like the Gift of Slaanesh itself, which currently gives +5 devotees and +3 seductive influence per turn PER character's faction, so I stayed away from it because it's harder to control balance-wise
_Reward flavour text:_ The Dark Prince's power waxes so strongly that it can no longer be contained within the Realms of Chaos. Storms howl outwards from the polar gates, driving his servants onwards to commit countless unspeakable acts in his name.

* **Route II - Paradise Lost**
  * "Come, mortal. Gorge yourself on the blood of your beloved, slain by your own hands. Yet your lust and despair mingle into a delicious concotion. Then, and only then, will you know the sweet caress of the Dark Prince."
  * Spread 20 Marks of Slaanesh
  * Establish 10 Cults
  * **Reward**:
    * _Cult Following_: Hero action cost: -30%, Hero action success chance: +20%, Hero starting rank +5
_Reward flavour text:_ Decadance leads to dalliance. Dalliance leads to debauchery. Debauchery leads to death.

* **Route III - The Dark Feast**
  * Let the arrogant fools indulge themselves in fine liquors, exotic sweetmeats and the pleasures of the flesh. Then they shall feast again, and indulge in pleasures of a different sort...
  * Vassalise 6 factions
  * The Dark Prince visited exquisite agony upon N'Kari for his failure to defeat the Exiled One. His wounded pride can only be salved with the sweet nectar of revenge...
  * Destroy factions:
    * Exiles of Khorne
  * **Reward**:
    * _Bound to the Blade_: Attribute: Causes Fear when fighting against Khornate factions
ALTERNATIVES FOR AGAINST KHORNE: Melee attack, weapon strength, leadership, melee defence, double experience gain
_Reward flavour text:_ Skarbrand's anguished soul now writhes within the Witstealer, granting the blade unparalleled strength.
    * _All The World's A Stage_: Recruit rank: %+3 for Daemonettes of Slaanesh and Exalted Daemonettes of Slaanesh units, Weapon strength: %+5% for Daemonettes of Slaanesh, Exalted Daemonettes of Slaanesh, Chaos Warriors of Slaanesh and Marauders of Slaanesh units
_Reward flavour text:_  And all the men and women merely playthings for the Daemonettes.

__________________________________________________

# Slaanesh - IMMORTAL EMPIRES

## N'Kari - Seducers of Slaanesh

* **Route I - The Great Game**
  * Though Slaanesh is presently the least of the four great Ruinous Powers, his brothers secretly fear him, for he feeds on humanity's darkest urges, a source of power that they cannot hope to match. Let the lands of Ulthuan be submerged beneath a writhing, twitching blanket of sin.
  * Achieve the highest corruption in a minimum of 100 regions
  * Occupy provinces: Caledor, Tiranoc, Nagarythe, Chrace, Cothique, Northern Yvresse, Southern Yvresse, Eataine, Ellyrion, Avelorn, Saphery.
  * **Reward**:
    * _Slaanesh Ascendant_: Leadership +10 when fighting against Elves (factionwide), Weapon strength +10% (N'Kari)
Alternatives: could also buff things like the Gift of Slaanesh itself, which currently gives +5 devotees and +3 seductive influence per turn PER character's faction, so I stayed away from it because it's harder to control balance-wise
_Reward flavour text:_ The Dark Prince's power waxes so strongly that it can no longer be contained within the Realms of Chaos. Storms howl outwards from the polar gates, driving his servants onwards to commit countless unspeakable acts in his name.

* **Route II - Paradise Lost**
  * "Come, mortal. Gorge yourself on the blood of your beloved, slain by your own hands. Yet your lust and despair mingle into a delicious concotion. Then, and only then, will you know the sweet caress of the Dark Prince."
  * Spread 20 Marks of Slaanesh
  * Establish 10 Cults
  * **Reward**:
    * _Cult Following_: Hero action cost: -30%, Hero action success chance: +20%, Hero starting rank +5
_Reward flavour text:_ Decadance leads to dalliance. Dalliance leads to debauchery. Debauchery leads to death.

* **Route III - The Dark Feast**
  * Let the arrogant fools indulge themselves in fine liquors, exotic sweetmeats and the pleasures of the flesh. Then they shall feast again, and indulge in pleasures of a different sort...
  * Vassalise 6 factions
  * The Arch-Temptor has been thwarted by Aenarion and his hated descendants more times than he would care to admit. The time has come to visit upon them the most exquisite of agonies. Only after they beg for death will their souls be relinquished to the Dark Prince.
  * Destroy factions:
    * Eatine, Order of Loremasters, Naggaroth
  * **Reward**:
    * _Aenarion's Blood_: Allegiance points gained for all factions: +25%, tribute from vassals +100%, Devotees per turn +40,
_Reward flavour text:_ Aenarion's final humiliation is at hand. Vengeance never tasted so sweet...
    * _All The World's A Stage_: Recruit rank: %+3 for Daemonettes of Slaanesh and Exalted Daemonettes of Slaanesh units, Weapon strength: %+5% for Daemonettes of Slaanesh, Exalted Daemonettes of Slaanesh, Chaos Warriors of Slaanesh and Marauders of Slaanesh units
_Reward flavour text:_  And all the men and women merely playthings for the Daemonettes.

**Comment by OhManTFE** [comment]
## N'KARI - Seducers of Slaanesh
Route I - The Ruination of the Elves
* Occupy all of Ulthuan

Route II - Aenarion Bloodline
* Destroy factions: Tyrion, Teclis, Malekith

Route II - Occupy Lothern, Gaean Vale, Oak of Ages, Naggarond
Route III - Nowhere is safe. The Elves of the forests think they are safe from your gaze. Tear down the waystones, set their sacred oak aflame. Give their souls to Slaanesh.
* Raze Oak of Ages

Route III - Insidious Influence
* Spread X Marks of Slaanesh, construct X cults

**Comment by msolefonte** [comment]
Btw, I think you already noticed, but you can edit my main comment instead of using a reply. Nothing to do with N'Kari tho

**Comment by MichaelBrown08** [comment]
Having played an N'kari campaign and been sorely disappointed you **had** to destroy the elves instead of subjugation I'd suggest keeping that in mind in route objectives. N'kari has a lot of diplomatic potential, and I think players want that from his campaign.

**Comment by msolefonte** [comment]
I completely forgot, but for N'Kari, Kairos and Ku'gath I would like to keep the **The Great Game** route, based on achieving the highest corruption in a minimum of 100 regions. A script for that is already coded.

**Comment by OhManTFE** [comment]
Could do Great Game, but it has issues.

1. It is a flavourless and directionless campaign, with no objective except expand everywhere and anywhere. Is this really what we're going for?
2. It is a very badly tuned mechanic at present (CA of course may patch this one day). I have played nearly 200 turn campaigns and only had 3 of the 4 objectives unlocked...
3. The rewards you unlock are very lackluster, especially seeing how long they take to unlock. Some of them, like ones that immobilise your army for 2 turns, aren't even worth the 2 turns you lose.

Solution: Make the Great Game objective part of a route but not the whole route.
