### ISSUE TITLE
TZE - Oracles of Tzeentch

### ISSUE THREAD

**Issue by msolefonte** [msolefonte/vco#50]
Kairos
Route I - Looking Forward
Kairos wants artifacts from this place.
* Destroy factions: Teclis, Kroq-gar, Thorek
* Occupy Karak Zorn (reward: magic drop chance)

Route II - Looking Back
* Destroy factions: Oxyotl, Tehenhauin
* Raze Itza

Route III - Wealth of Knowledge
* Unlock all Changers of Ways

**Comment by msolefonte** [comment]
The Great Game: Achieve the highest corruption in a minimum of 100 regions

**Comment by Mjb141** [comment]
Should merge 1 & 2 I think.  Something like:

Perhaps: 

```Route I: Threats from Then and Now
Kairos' visions of the future see a threat from the west. The powerful Chameloen Skink Oyxotl is preparing to strike at servants of Chaos, and his elimination has been foreseen.
 * Destroy factions:
   * Ghost of Pahuax
 * Control provinces:
   * The Ice-Fire Plains
Kairos' visions of the past reveal powerful artifacts hidden away by the learned lizards in their dense jungles.
  * Destroy factions:
    * Teclis, Kroq
  * Occupy <somewhere in lizard jungle>
```

Then add `The great game`, then keep `wealth of knowledge` (but expand it a bit).
