### ISSUE TITLE
CHS - Warhost of the Apocalypse

### ISSUE THREAD

**Issue by msolefonte** [msolefonte/vco#54]
# Warriors of Chaos

## Archaon - Warhost of the Apocalypse
* **Route I - The Beginning of the End**
  * There are those who would stand against your ascension. Your Father-in-Shadow schemes against you on Albion, the upstart "Godslayer" means to challenge your reign, and the Red Tzar oversteps his bounds, leading an expedition deep into the Chaos Wastes. They will all bend the knee, or they will all die.
  * Destroy or vassalise factions:
    * Ursun Revivalists, Legion of Chaos, Shadow Legion
  * Overwrite text: Occupy at least 3 of the following Dark Fortresses:
  * Occupy the following regions:
    * Writhing Fortress, The Howling Citadel, The Crystal Spires, Black Rock, Karak Dum, Karak Vlag
  * **Reward**:
    * _Dark Coronation_: Souls gained from battles: +10%, All Authority +2 (Archaon's army)
_Reward flavour text:_ With a pulse of eldritch force, the Crown of Domination is placed upon your head. A vast ocean of battle-hardened warriors chants your name. You take up your blade and mount your steed, ready to march south to bring ruination and death to the world.
wh_dlc01_item_passive_the_crown_of_domination.png

* **Route II - The End Times**
  * "Fear me mortals, for I am the Anointed, the favoured Son of Chaos, the Scourge of the World. The armies of the gods rally behind me, and it is by my will and by my sword that your weakling nations shall fall."
  * Destroy or vassalise factions:
    * Ice Court, Middenheim, Reikland
 * Occupy Middenheim either directly or via diplomacy.
  * Win 50 battles.
  * **Reward**:
    * _The Gateway of Fauschlag_: +10 Chaos Undivided corruption in adjacent provinces factionwide, warband upgrade cost -30% for Undivided units, Gifted units pool capacity: +2 for Keepers of Secrets, Bloodthirsters, Lords of Change and Great Unclean Ones.
_Reward flavour text:_ Deep beneath Middenheim there lies an ancient device, left from the age when the gods warred against the Old ones; a device that, if properly coaxed, will unleash a rift to the Realm of Chaos.
icon_spell_vortex.png

* **Route III - Slayer of Kings**
  * U'zhul, the daemon trapped within your blade, rages against your will, eager to taste the blood of kings. It is time to slake its thirst.
  * Occupy at least 4 of the following regions either directly or via vassals:
    * Altdorf, Kislev, Couronne, Lair of the Troll King, Karaz-a-Karak, The Oak of Ages, Khemri 
// OR
  * (script required) Destroy or vassalise at least 3 of the following factions: Wintertooth, Bretonnia, Karaz-a-Karak, Talsyn, Khemri, Naggarond
  * Occupy, loot, raze or sack 50 settlements.
  * **Reward**:
    * _U'zhul's Fate_: You will be presented with a dilemma.
wh_dlc01_weapon_abilities_the_slayer_of_kings.png
DILEMMA TITLE: U'Zhul's Fate
DILEMMA TEXT: "Release me from this steel thralldom, Everchosen, so that I may kill for mighty Khorne once more. To taste the blood he spills, rather than watch it drip down the walls of my prison. To wield, and not be wielded. You swore I would be free! You swore!"
OPTION 1: U'zhul Unbound: "You are free, daemon. Free to serve as my pack mule. Now go, search the corpses of the slain. Bring back anything of value you find."
OPTION 1 REWARDS: -20% Weapon strength for Archaon, income from post-battle loot: +50%, magic find for Archaon: +50%
item_ability.png
OPTION 2: U'zhul Denied: "I said I would set you free, mighty daemon. I never said when."
OPTION 2 REWARDS: Weapon strength: +20% for Archaon, Ward save: +20% for Archaon
wh_dlc01_weapon_abilities_the_slayer_of_kings.png

**Comment by OhManTFE** [comment]
So the Gateway of Fauschlag is literally what causes the end of the world in End Times. I nerfed it significantly, as you can see, but if you guys want, we can discuss some seriously OP stuff if you want to honour its godlike importance to the lore.

**Comment by msolefonte** [comment]
Create a PR with the design pls :D
