### ISSUE TITLE
DEF - Har Ganeth

### ISSUE THREAD

**Issue by msolefonte** [msolefonte/vco#82]

**Comment by MichaelBrown08** [comment]
My original Har Ganeth suggestion:

Route 1: **Sacrifice and slaughter**
- Text: Nagarythe has lived too long, and Khaine hungers for the blood of the revenant. The Shadow King is close, and his time is near.
- Objective: Destroy faction:
  - Nagarythe.
- Text: Our dedication must not falter, our worship must not cease. Our shrine calls to us, and new sacrifices must be made.
- Objective: Control Settlement: 
  - Shrine of Khaine

That route is fairly clear - Nagarythe are right below your start position and they're hunting Malekith and all Dark Elves. Slaughter them as Hellebron and her cult would. Then, the Shrine of Khaine lies below the ruins of Nagarythe, right at the peak of Ulthuan. 

Route 2: **Suffer not another queen to live**
- Text: There shall be one queen, and it shall be I, Blood Queen of Khaine. Slay the Everqueen.
- Objective: Destroy faction:
  - Avelorn.
- Text: Text: Tyrion, The heir of aenarion, Consort of alarielle, still lives. High Elf slaves whisper to him in their mindlessness, they believe he'll one day wear the Phoenix Crown. Rip their dreams asunder.
- Objective: Destroy faction:
  - Eataine.

Alarielle and Tyrion are essentially a pair and would make the greatest of sacrifices to Khaine. It'll be a tough route - Ulthuan is almost always defensive/militarily allied, and these two factions rarely if ever are taken out by the AI, so there won't be any shortcuts.

Route 3: **An eternity of blood**

- Text: Morathi has spurned you too many times. She has long denied you access to the Cauldrons of Blood, and the eternal youth within them, but no more.
- Objective: Destroy faction: 
  - Cult of Pleasure
- Objective: Control settlement: 
  - Ancient City of Quintex
- Objective: Landmark: 
   - Sanctum of Quintex

This route is Hellebron's ultimate goal - eternal youth from the cauldrons.
